# Configuration file for Monkey Patches
# This file controls which patches are enabled and other mod settings.
# 
# Note: Patches will only load if the target mod is installed.
# Use the startup logs to see which patches are active.

[patches]
	# KubeJS Patches
	# Patches for the KubeJS mod
	# These patches will only load if KubeJS is installed
	[patches.kubejs]
		# Enable KubeJS issue #972 patches
		# Fixes assumptions about concrete builder types that could cause ClassCastException
		# Includes ServerScriptManagerMixin and KubeJSModEventHandlerMixin
		# Status in logs: ENABLED / DISABLED / MOD NOT LOADED
		gh972_enabled = true

	# Subtle Effects Patches
	# Patches for the Subtle Effects mod
	# These patches will only load if Subtle Effects is installed
	[patches.subtle_effects]
		# Enable Subtle Effects issue #113 patches
		# Fixes NeoForge crashing with End Remastered installed
		# Changes block ticker registration to use predicate-based registration
		# Status in logs: ENABLED / DISABLED / MOD NOT LOADED
		gh113_enabled = true

	# PortableTanks Patches
	# Patches for the PortableTanks mod
	# These patches will only load if PortableTanks is installed
	[patches.portabletanks]
		# Enable PortableTanks issue #12 patches
		# Fixes NullPointerException in PortableTankItem$ItemFluidHandler.getFluid()
		# Prevents crashes when accessing fluid data from ItemStacks without proper NBT data
		# Status in logs: ENABLED / DISABLED / MOD NOT LOADED
		gh12_enabled = true

	# Create Stuff 'N Additions Patches
	# Patches for the Create Stuff 'N Additions mod
	# These patches will only load if Create Stuff 'N Additions is installed
	[patches.create_sa]
		# Enable Create Stuff 'N Additions issue #59 capabilities
		# Adds Neoforge fluid handler capabilities to enable e.g. Create spout filling
		# Allows jetpacks and tanks to be filled using Create spouts and other fluid systems
		# Status in logs: ENABLED / DISABLED / MOD NOT LOADED
		fluid_handler_capabilities_enabled = true

	# Just Enough Resources Patches
	# Patches for the Just Enough Resources mod
	# These patches will only load if Just Enough Resources is installed
	[patches.jeresources]
		# Enable Just Enough Resources issue #547 patch
		# Prevents missing JER tabs when using modded biomes
		# Status in logs: ENABLED / DISABLED / MOD NOT LOADED
		gh547_enabled = true

	# Patchouli Patches
	# Patches for the Patchouli mod
	# These patches will only load if Patchouli is installed
	[patches.patchouli]
		# Enable Patchouli issue #790 patch
		# Prevents registry access issues during book loading
		# Fixes CommandSyntaxException when loading custom book items before mod registration
		# Status in logs: ENABLED / DISABLED / MOD NOT LOADED
		gh790_enabled = true
